<!DOCTYPE html>
<html data-enhance="false" lang="en" xmlns="https://www.w3.org/1999/html" id="helloHjmo">
<head data-enhance="false"><meta http-equiv="Content-Type" content="text/html; charset=utf-8">

	<meta name="description" content="Find list of free food centers during COVID-19 outbreak.">
	<meta name="keywords" content="free food, Covid free food, Coronovirus Free Food, Community Kitchens">
	<meta name="google-site-verification" content="X0_EhVGmTWu5ecqt4qRBGW1SUZ-ZWPVlwzdlR48CsEo" />




	<meta property="og:url"                content="http://zerofood.in" />
	<meta property="og:type"               content="article" />
	<meta property="og:title"              content="Zero Food - A List of free food centers across India" />
	<meta property="og:description"        content="Find free food centers across India" />
	<meta property="og:image"              content="<?php echo $gama['config']['themeUrl']; ?>/images/eradicate.jpeg" />



	<meta name="twitter:card" content="This wesbite helps poor people not go hungry" />
	<meta name="twitter:site" content="@ZeroFoodIn" />
	<meta name="twitter:creator" content="@ZeroFoodIn" />	
	<meta name="viewport" content="width=device-width,initial-scale=1, user-scalable=no">
	<link href="https://allfont.net/allfont.css?fonts=ad-lib-bt" rel="stylesheet" type="text/css" />


	<!-- Latest compiled and minified CSS -->
	<link rel="shortcut icon" type="image/x-icon" href="<?php echo $gama['config']['themeUrl']; ?>/images/favicon.png" />
	<link rel="icon" href="<?php echo $gama['config']['themeUrl']; ?>/images/favicon.ico">
	<link type="text/css" rel="stylesheet" href="<?php echo $gama['config']['themeUrl']; ?>/assets/css/style.css?v=<?php //echo filemtime($_SERVER["DOCUMENT_ROOT"]."/themes/ehthree/assets/css/style.css") ?>" data-no-instant>
	<link type="text/css" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" >
	<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet" >
	<link type="text/css" rel="stylesheet" type="text/css" href="<?php echo $gama['config']['themeUrl']; ?>/assets/css/select22.min.css" />
	<link type="text/css" rel="stylesheet" href="<?php echo $gama['config']['themeUrl']; ?>/assets/css/inputTags.css" rel="stylesheet" >
	<link rel="stylesheet" href="<?php echo $gama['config']['themeUrl']; ?>/assets/css/bootstrap-material-datetimepicker.css" />
	<link rel="stylesheet" href="<?php echo $gama['config']['themeUrl']; ?>/assets/special/css/bootstrap.min.css" />
	<link rel="stylesheet" href="<?php echo $gama['config']['themeUrl']; ?>/assets/special/css/custom.css" />
	<link rel="stylesheet" href="<?php echo $gama['config']['themeUrl']; ?>/assets/special/css/ionicons.min.css" />
	<link rel="stylesheet" href="<?php echo $gama['config']['themeUrl']; ?>/assets/special/css/jquery.dataTables.min.css" />
	<link rel="stylesheet" href="<?php echo $gama['config']['themeUrl']; ?>/assets/special/css/pace.css" />

	<!-- Latest compiled and minified JavaScript -->


	<script type="application/x-javascript" src="<?php echo $gama['config']['themeUrl']; ?>/assets/js/library/jquery-1.11.min.js" ></script>

	<script type="application/x-javascript" src="<?php echo $gama['config']['themeUrl']; ?>/assets/js/library/jqueryui.min.js" ></script>
	<script type="application/x-javascript" src="<?php echo $gama['config']['themeUrl']; ?>/assets/js/library/jquery.easing.min.js" ></script>
	<script type="text/javascript" src="<?php echo $gama['config']['themeUrl']; ?>/assets/js/bootstrap-material-datetimepicker.js" ></script>
	<script type="text/javascript" src="<?php echo $gama['config']['themeUrl']; ?>/assets/special/js/bootstrap.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" ></script>
	<script type="text/javascript" src="<?php echo $gama['config']['themeUrl']; ?>/assets/special/js/modernizr.custom.js"></script>
	<script type="text/javascript" src="<?php echo $gama['config']['themeUrl']; ?>/assets/special/js/pace.min.js"></script>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-163391752-1"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'UA-163391752-1');
	</script>





	<!-- Hotjar Tracking Code for http://www.zerfood.in -->
	<script>
		(function(h,o,t,j,a,r){
			h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
			h._hjSettings={hjid:1764424,hjsv:6};
			a=o.getElementsByTagName('head')[0];
			r=o.createElement('script');r.async=1;
			r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
			a.appendChild(r);
		})(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
	</script>




	<?php
	if ($gama['config']['soft_links'] == 1) {
		echo '<script>function gama_zone(){return \'' . $gama['config']['helper'] . '\';}</script>';
	} else {
		echo '<script>function gama_zone(){return \'https://zerofood.xyz/api\';}</script>';
	}

	echo '<script>function gamaTwo_zone(){return \'' . $gama['config']['helper'] . '\';}</script>';
	?>

	<?php echo GAMA_getPage('header'); ?>

	<?php echo $gama['content']; ?>
	<?php echo GAMA_getPage('footer'); ?>
</div>
</body>

<script type="application/x-javascript" src="<?php echo $gama['config']['themeUrl']; ?>/assets/js/instantclick.min.js"  data-no-instant></script>


<script type="application/x-javascript" src="<?php echo $gama['config']['themeUrl']; ?>/assets/js/core.js?v=<?php //echo filemtime($_SERVER["DOCUMENT_ROOT"]."/themes/ehthree/assets/js/core.js") ?>" 
	data-no-instant data-instant-track></script>

	<script>InstantClick.init();</script>
	<script type="text/javascript" src="<?php echo $gama['config']['themeUrl']; ?>/assets/special/js/script.js"></script>
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVwxnd6JIKA0MUETDExhgHtXRcLL77Kuo&libraries=places"></script>
	<script type="text/javascript" src="<?php echo $gama['config']['themeUrl']; ?>/assets/maps/maps.js"></script>
	<script type="text/javascript" src="<?php echo $gama['config']['themeUrl']; ?>/assets/maps/mapsfill.js"></script>

	<script type="application/x-javascript" src="<?php echo $gama['config']['themeUrl']; ?>/assets/js/library/jquery.color.min.js" ></script>
	<script type="application/x-javascript" src="<?php echo $gama['config']['themeUrl']; ?>/assets/js/fontAwesome.min.js"></script>




