<div class="footer">
    <footer id="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">

                    <p class="copyright">A community effort By Anonymous Citizens</p>


                </div>
            </div>
        </div>
    </footer>

</div>
<br/>
<div class="col-md-4 col-md-offset-4">

<a href="https://t.me/zerofoodIndia" target="_blank" class="btn btn-info btn-block" role="button">Join Telegram</a>

<br>
<p class="text-center"> <a href="<?php echo $gama['config']['siteUrl']; ?>/disclaimer">Disclaimer</a> </p>
</div>
<div class="ehMainLoader">
<div class="center"><img src="<?php echo $gama['config']['themeUrl']; ?>/images/loader.gif"/></div>
</div>
<div class="ehMainAjaxResult">

</div>
<div class="eh-backdrop"></div>
<div class="eh-backdropOne"></div>
