
<title>Contact us - COVID FOOD</title>
<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-12">
                <h1 class="page-title">Contact</h1>
                <article class="post">
                    <div class="entry-content clearfix">
                        <form action="#" method="post" class="contact-form" onsubmit="return false;">
                            <div class="row">
                                <div class="col-md-6 col-md-offset-3">
                                    <input type="text" name="name" id="name" placeholder="Name" required>
                                    <input type="email" name="email" id= "email" placeholder="Email" required>
                                    <input type="text" name="subject" id="subject" placeholder="Subject" required>
                                    <textarea name="message" rows="7" id="matter" placeholder="Your Message" required></textarea>
                                    <button onclick="contactForm();" class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Drop Me a Line</span></button>
                                </div>
                            </div>	<!-- row -->
                        </form>
                    </div>
                </article>
            </main>
        </div>
    </div>
</div>
<!--Start of Tawk.to Script-->
<script type="text/javascript">
	var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
	(function(){
		var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
		s1.async=false;
		s1.src='https://embed.tawk.to/5e916dac69e9320caac2819d/default';
		s1.charset='UTF-8';
		s1.setAttribute('crossorigin','*');
		s0.parentNode.insertBefore(s1,s0);
	})();
	
	InstantClick.on('change', function(){
	    	var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
	(function(){
		var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
		s1.async=false;
		s1.src='https://embed.tawk.to/5e916dac69e9320caac2819d/default';
		s1.charset='UTF-8';
		s1.setAttribute('crossorigin','*');
		s0.parentNode.insertBefore(s1,s0);
	})();
	});
</script>
<!--End of Tawk.to Script-->
