<title>Create a Food Center - COVID 19</title>
<input type="text" style="display:none;" class="addPostFormHolderInput inputEventStartDate twoInputsLeft eventStreetOne" id="street_number"   name="businessStreetAddressOne" placeholder="Street Address"/>
<input type="text" style="display:none;"  class="addPostFormHolderInput inputEventEndDate twoInputsRight eventStreetTwo" id="route"   name="businessStreetAddressTwo" placeholder="Street Address 2"/>
<input type="text" style="display:none;"  class="addPostFormHolderInput oneFourth eventCity" id="locality"   name="businessCity" placeholder="City"/>
<input type="text" style="display:none;"  class="addPostFormHolderInput oneFifth marginleft30 eventState" id="administrative_area_level_1"   name="businessState" placeholder="State"/>
<input type="text" style="display:none;"  class="addPostFormHolderInput oneFifth marginleft30 eventCountry" id="country"   name="businessCountry" placeholder="Country"/>
<input type="text" style="display:none;"  class="addPostFormHolderInput oneFifth marginleft30 eventPostalCode" id="postal_code"   name="businessZipCode" placeholder="Zip Code"/>
<input type="text" style="display:none;"  class="addPostFormHolderInput oneFifth marginleft30" id="token"   name="businessZipCode" value="<?php  echo $_SESSION['userToken']?>" placeholder="Zip Code"/>
<input type="text" style="display:none;"  class="addPostFormHolderInput oneFifth marginleft30" id="userIdentity"   name="businessZipCode" value="<?php  echo $_SESSION['userIdentity']?>" placeholder="Zip Code"/>

<div class="container">

<div class="row align-items-center" style="margin-bottom: 2rem;">
     
     <span style="margin: 4rem;"> <h3>Create a new Food Center Entry</h3></span>
               </div>


<script>
  var lat = 18.35827827454; //default latitude
var lng = 121.63744354248; //default longitude
  </script>
<form class="form-horizontal" id="createFoodCenterForm" onsubmit="return false;">
<fieldset>


<!-- Text input-->
<div class="form-group">
<label class="col-md-4 control-label" for="Place_Name_id">Place Name</label>  
<div class="col-md-4">
<input id="Place_Name_id" name="Place_Name_id" placeholder="Place name" class="form-control input-md" required="" type="text">

</div>
</div>

<!-- Select Basic -->
<div class="form-group">
<label class="col-md-4 control-label" for="State_id">State</label>
<div class="col-md-4">
<input type="text" id="State_id" placeholder="State" class="form-control">


</div>
</div>

<!-- Select Basic -->
<div class="form-group">
<label class="col-md-4 control-label" for="State_id">City/District</label>
<div class="col-md-4">
<input type="text" id="city_id" placeholder="City" class="form-control">


</div>
</div>



<!-- Textarea -->
<div class="form-group">
<label class="col-md-4 control-label" for="address_description">Address</label>
<div class="col-md-4">                     
<textarea class="form-control " placeholder="Full Postal Address" id="address_description" name="address_description"></textarea>
</div>
</div>


<!-- Time Basic -->
<div class="form-group">
<label class="col-md-4 control-label" for="Lunch_time">Lunch Timing </label>
<div class="col-md-4">
<div class="col-xs-6" style="padding-left:  0px;">    
<input type="time" id="lunchTimeFrom" class="form-control">
    </div>


<div class="col-xs-6"  style="padding-right: 0px;"> 
  <input type="time" id="lunchTimeTo" class="form-control">
</div>
</div>
</div>


<!-- Time Basic -->
<div class="form-group">
<label class="col-md-4 control-label" for="Dinner_time">Dinner Timing</label>
<div class="col-md-4">

<div class="col-xs-6" style="padding-left:  0px;">    
      <input type="time" id="dinnerTimeFrom" class="form-control">
            </div>


       <div class="col-xs-6"  style="padding-right: 0px;"> 
          <input type="time" id="dinnerTimeTo" class="form-control">
</div>

</div>
</div>



<!-- Text input-->
<div class="form-group">
<label class="col-md-4 control-label" for="capacity_id">Capacity</label>  
<div class="col-md-4">
<input id="capacity_id" name="capacity_id" placeholder="100" class="form-control input-md" required="" type="text">

</div>
</div>

<!-- Text input-->
<div class="form-group">
<label class="col-md-4 control-label" for="contact_id">Contact</label>  
<div class="col-md-4">
<input id="contact_id" name="contact_id" placeholder="9XXXXXXXXX" class="form-control input-md" required="" type="text">

</div>
</div>


<!-- Text input-->
<div class="form-group">
<label class="col-md-4 control-label" for="Location_id">Location</label>  
<div class="col-md-4">
<input type="text" class="form-control input-md companyLocation addPostFormHolderInput fullInput eventFullLocation" id="autocomplete"  onFocus="geolocate();" name="mapLocation" placeholder="Shilparamam, Madhapur Road, Jubilee Enclave, HITEC City, Hyderabad, Telangana, India"/>

<div id="map_canvas"></div>

</div>
</div>

<!-- Text input-->
<div class="form-group">
<label class="col-md-4 control-label" for="author">AUTHOR</label>  
<div class="col-md-4">
<input id="author" name="author" value="<?php echo $_SESSION['fullName']?>" placeholder="AUTHOR" class="form-control input-md" required="" readonly type="text">

</div>
</div>
<!-- Button -->
<div class="form-group">

<div class="col-md-4 col-md-offset-4">
<button id="singlebutton"  name="singlebutton" style="margin-right: 20px; " class="btn btn-success active" onclick="createFoodCenter();">Create</button>
</div>

</fieldset>
</form>

