<div class="container">
				<div class="row">
					<div class="col-md-6 col-md-offset-3">

						<h1 class="page-title">Disclaimer</h1>
						
<p class="text-center">
    

We don't claim accuracy of the data on our website, as this is a crowdsourced data which has not been through vetting process. Please verify with other sources for information accuracy. 

All the data present on the website is contributed by users and we are not resposible for any privacy violations occured, in-case if you find you that
your personal data is present on our website. Please report immediately through chat or contact option.

Alternatively you can also reach us on reach (at) zerofood.in

</p>

					</div>
				</div>
			</div>