<title>Edit a Food Center - COVID 19</title>
<script>
var lat = <?php echo $_GET['lat']?>; //default latitude
var lng = <?php echo $_GET['lng']?>; //default longitude

function initMap() {
  // The location of Uluru
  var uluru = {lat: lat, lng: lng};
  // The map, centered at Uluru
  var map = new google.maps.Map(
      document.getElementById('map'), {zoom: 4, center: uluru});
  // The marker, positioned at Uluru
  var marker = new google.maps.Marker({position: uluru, map: map});
}
function getFoodCenterDetails(){

$.ajax({
        type: "GET",
        headers: {
            'Authorization': 'Bearer <?php echo $_SESSION['userToken']?>',
        },
		url: gama_zone()+"/food-centers/<?php echo $_GET['gamaTwo'];?>",
		dataType: 'json',
        contentType: 'application/json',
        data: "", 
		cache: false,
		beforeSend: function() {
			
			},
		success: function(html) {
            var lat = html.location.coordinates[1];
            var lng = html.location.coordinates[0];
            $('#Place_Name_id').val(html.name);
            $('#State_id').val(html.state);
            $('#city_id').val(html.city);
            $('#address_description').val(html.address);
            $('#lunchTimeFrom').val(html.timings.lunch.start);
            $('#lunchTimeTo').val(html.timings.lunch.end);
            $('#dinnerTimeFrom').val(html.timings.dinner.start);
            $('#dinnerTimeTo').val(html.timings.dinner.end);
            $('#capacity_id').val(html.capacity);
            $('#contact_id').val(html.contactNumber);
            $('#autocomplete').val(html.location.googleAddress);
            $('#status').val(html.status);
                
            new google.maps.LatLng(lat, lng);
		}
});
}
getFoodCenterDetails();
</script>
<input type="text" style="display:none;" class="addPostFormHolderInput inputEventStartDate twoInputsLeft eventStreetOne" id="street_number"   name="businessStreetAddressOne" placeholder="Street Address"/>
<input type="text" style="display:none;"  class="addPostFormHolderInput inputEventEndDate twoInputsRight eventStreetTwo" id="route"   name="businessStreetAddressTwo" placeholder="Street Address 2"/>
<input type="text" style="display:none;"  class="addPostFormHolderInput oneFourth eventCity" id="locality"   name="businessCity" placeholder="City"/>
<input type="text" style="display:none;"  class="addPostFormHolderInput oneFifth marginleft30 eventState" id="administrative_area_level_1"   name="businessState" placeholder="State"/>
<input type="text" style="display:none;"  class="addPostFormHolderInput oneFifth marginleft30 eventCountry" id="country"   name="businessCountry" placeholder="Country"/>
<input type="text" style="display:none;"  class="addPostFormHolderInput oneFifth marginleft30 eventPostalCode" id="postal_code"   name="businessZipCode" placeholder="Zip Code"/>
<input type="text" style="display:none;"  class="addPostFormHolderInput oneFifth marginleft30" id="token"   name="businessZipCode" value="<?php  echo $_SESSION['userToken']?>" placeholder="Zip Code"/>
<input type="text" style="display:none;"  class="addPostFormHolderInput oneFifth marginleft30" id="userIdentity"   name="businessZipCode" value="<?php  echo $_SESSION['userIdentity']?>" placeholder="Zip Code"/>

<div class="container">

<div class="row align-items-center" style="margin-bottom: 2rem;">
     
     <span style="margin: 4rem;"> <h3>Edit Food Center</h3></span>
               </div>



<form class="form-horizontal" id="createFoodCenterForm" onsubmit="return false;">
<fieldset>


<!-- Text input-->
<div class="form-group">
<label class="col-md-4 control-label" for="Place_Name_id">Place Name</label>  
<div class="col-md-4">
<input id="Place_Name_id" name="Place_Name_id" placeholder="Place name" class="form-control input-md" required="" type="text">

</div>
</div>

<!-- Select Basic -->
<div class="form-group">
<label class="col-md-4 control-label" for="State_id">State</label>
<div class="col-md-4">
<select id="State_id" name="State_id" class="form-control">
<option>Andhra Pradesh</option>
<option>Telangana</option>
<option>Delhi</option>
<option>Kerala</option>
</select>

</div>
</div>

<!-- Select Basic -->
<div class="form-group">
<label class="col-md-4 control-label" for="State_id">City/District</label>
<div class="col-md-4">
<select id="city_id" name="State_id" class="form-control">
<option>Hyderabad</option>
<option>Karimnagar</option>
<option>Warangal</option>
<option>Adlialabad</option>
</select>

</div>
</div>



<!-- Textarea -->
<div class="form-group">
<label class="col-md-4 control-label" for="address_description">Address</label>
<div class="col-md-4">                     
<textarea class="form-control " id="address_description" name="address_description"></textarea>
</div>
</div>


<!-- Time Basic -->
<div class="form-group">
<label class="col-md-4 control-label" for="Lunch_time">Lunch Timing </label>
<div class="col-md-4">
<div class="col-xs-6" style="padding-left:  0px;">    
<input type="time" id="lunchTimeFrom" class="form-control">
    </div>


<div class="col-xs-6"  style="padding-right: 0px;"> 
  <input type="time" id="lunchTimeTo" class="form-control">
</div>
</div>
</div>


<!-- Time Basic -->
<div class="form-group">
<label class="col-md-4 control-label" for="Dinner_time">Dinner Timing</label>
<div class="col-md-4">

<div class="col-xs-6" style="padding-left:  0px;">    
      <input type="time" id="dinnerTimeFrom" class="form-control">
            </div>


       <div class="col-xs-6"  style="padding-right: 0px;"> 
          <input type="time" id="dinnerTimeTo" class="form-control">
</div>

</div>
</div>



<!-- Text input-->
<div class="form-group">
<label class="col-md-4 control-label" for="capacity_id">Capacity</label>  
<div class="col-md-4">
<input id="capacity_id" name="capacity_id" placeholder="100" class="form-control input-md" required="" type="text">

</div>
</div>

<!-- Text input-->
<div class="form-group">
<label class="col-md-4 control-label" for="contact_id">Contact</label>  
<div class="col-md-4">
<input id="contact_id" name="contact_id" placeholder="9XXXXXXXXX" class="form-control input-md" required="" type="text">

</div>
</div>


<!-- Text input-->
<div class="form-group">
<label class="col-md-4 control-label" for="Location_id">Location</label>  
<div class="col-md-4">
<input type="text" class="form-control input-md companyLocation addPostFormHolderInput fullInput eventFullLocation" id="autocomplete"  onFocus="geolocate();" name="mapLocation" placeholder="Shilparamam, Madhapur Road, Jubilee Enclave, HITEC City, Hyderabad, Telangana, India"/><span syyle="display: inline; width:200px;height:100px;"id="map"></span>

<div id="map_canvas"></div>

</div>
</div>

<!-- Text input-->
<div class="form-group">
<label class="col-md-4 control-label" for="author">AUTHOR</label>  
<div class="col-md-4">
<input id="author" name="author" value="<?php echo $_SESSION['fullName']?>" placeholder="AUTHOR" class="form-control input-md" required="" readonly type="text">

</div>
</div>
<?php
if($_SESSION['userRole'] != "admin"){
?>
<div class="form-group">
<label class="col-md-4 control-label" for="status">Status</label>  
<div class="col-md-4">
<input style="display: none;"  id="status" read-only name="status"  placeholder="AUTHOR" class="form-control input-md" required="" readonly type="text">

</div>
</div>
<?php 
} else {
    ?>

<div class="form-group">
<label class="col-md-4 control-label" for="status">Status</label>
<div class="col-md-4">
<select id="status" name="status" class="form-control">
<option Value="LISTED">LISTED</option>
<option Value="UNLISTED">UNLISTED</option>
<option Value="DELETED" >DELETED</option>
</select>
<?php
}
?>
</div>
</div>
<!-- Button -->
<div class="form-group">

<div class="col-md-4 col-md-offset-4">
<button id="singlebutton"  name="singlebutton" style="margin-right: 20px; " class="btn btn-success active" onclick="updateFoodCenter('<?php echo $_GET['gamaTwo'];?>','<?php echo $_SESSION['userIdentity'];?>');">Update</button>
</div>

</fieldset>
</form>

