<title>My Food Center List - COVID 19 FOOD</title>
<script>
function getMyList(){

$.ajax({
        type: "GET",
        headers: {
            'Authorization': 'Bearer <?php echo $_SESSION['userToken']?>',
        },
		url: gama_zone()+"/food-centers/users/<?php echo $_SESSION['userIdentity'];?>",
		dataType: 'json',
        contentType: 'application/json',
        data: "", 
		cache: false,
		beforeSend: function() {
			
			},
		success: function(html) {
            console.log(html);
            assignToEventsColumns(html);
            
		}
});
function assignToEventsColumns(data) {
    
    var table = $('#myTableOne').dataTable({
        paging: true,
        searching: true,
        "bAutoWidth" : false,
        "aaData" : data,
        "columns" : [ {
            "data" : "id", render: function (data, type, row, meta) {
        return meta.row + meta.settings._iDisplayStart + 1;
        }
        }, {
            "data" : "name"
        }, {
            "data" : "state"
        }, {
            "data" : "city"
        }, {
            "data" : "address"
        } ,{
            "data" : "timings",
            "render": function ( data, type, row ) {
                if(data) {
                    return '<span>Lunch: '+data.lunch.start+' - '+data.lunch.end+'<br/>Dinner: '+data.dinner.start+' - '+data.dinner.end+'</span>';
                } else {
                    return 'not available';
                }
            }
        } ,{
            "data" : "capacity"
        } ,{
            "data" : "contactNumber"
        } ,{
            "data" : "location",
            "render": function ( data, type, row ) {
                if(data) {
                    return '<a target="_blank" href="http://www.google.com/maps/place/'+data.coordinates[1]+','+data.coordinates[0]+'">View Map</a>';
                } else {
                    return 'not available';
                }
            }

        } ,{
            "data" : "status"
        } ,{
            "data" : "id",
            "render": function ( data, type, row ) {
                if(data) {
                    console.log(row.long);
                    return '<a target="_blank" href="<?php echo $gama['config']['siteUrl']; ?>/edit-food-center/'+data+'?lat='+row.lat+'&lng='+row.long+'">Edit</a>';
                } else {
                    return 'not available';
                }
            },
        } ,
    ],
    "columnDefs": [
        {"className": "dt-center", "targets": "_all"}
      ],
       
    })
}
}
getMyList();
</script>
<div class="container">

<div class="row align-items-center" style="margin-bottom: 2rem;">

  <div class="table-responsive">

   
   <span style="margin: 4rem;"> <h3>List of Entries</h3></span>
  <table class="table table-hover" id="myTableOne">
      <thead>
          <tr>
              <th scope="col">#</th>
              <th scope="col">Place name</th>
              <th scope="col">State</th>
              <th scope="col">City/District</th>
              <th scope="col">Address</th>                      
              <th scope="col">Timing</th>
              <th scope="col">Capacity</th>
              <th scope="col">Contact</th>
              <th scope="col">Location</th>
              <th scope="col">Status</th>
              <th scope="col">Action</th>
          </tr>
</thead>

</table>
</div>

        
          </div>

  </div>
